<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMaster.Master" AutoEventWireup="true" CodeBehind="CourseList.aspx.cs" Inherits="OnlineEnrollmentSystem.Admin.CourseList" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
     <table>
        <tr>
            <td>
                <%--<asp:Button ID="btnAddCourse" runat="server" Text="Add Course" OnClick="btnAddCourse_Click" />--%>
            </td>
            <td></td>
        </tr>
        <tr>
            <td>
                <asp:GridView ID="gvCourses" runat="server" class="table" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" HeaderStyle-BackColor="#3AC0F2" HeaderStyle-ForeColor="White" RowStyle-BackColor="#A1DCF2" AlternatingRowStyle-BackColor="White" RowStyle-ForeColor="#3A3A3A" AllowPaging="true" PageSize="10" OnRowCancelingEdit="gvCourses_RowCancelingEdit" OnRowDeleting="gvCourses_RowDeleting" OnRowEditing="gvCourses_RowEditing">
                    <Columns>
                        <asp:TemplateField HeaderText="CourseId" Visible="false">
                            <ItemTemplate>
                                <asp:Label ID="lblCourseId" runat="server" Text='<%#Eval("C_ID") %>' ></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Course Name">
                            <ItemTemplate>
                                <%#Eval("C_NAME") %>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <%--<asp:TemplateField HeaderText="Description">
                            <ItemTemplate>
                                <%#Eval("C_DESCRIPTION") %>
                            </ItemTemplate>
                        </asp:TemplateField>--%>
                        <asp:TemplateField HeaderText="Fee">
                            <ItemTemplate>
                                <%#Eval("C_FEE") %>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Duration">
                            <ItemTemplate>
                                <%#Eval("C_DURATION") %>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Start Date">
                            <ItemTemplate>
                                <%#Eval("C_STARTDATE") %>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="End Date">
                            <ItemTemplate>
                                <%#Eval("C_ENDDATE") %>
                            </ItemTemplate>
                        </asp:TemplateField>                        
                    </Columns>
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>
