<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMaster.Master" AutoEventWireup="true" CodeBehind="CourseFacultyEnrollment.aspx.cs" Inherits="OnlineEnrollmentSystem.Admin.CourseFacultyEnrollment" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="row">
        <div class="col-md-1">
            Select Course
        </div>
        <div class="col-md-3">
            <asp:DropDownList ID="ddlCourse" class="form-control" runat="server"></asp:DropDownList>
        </div>
        <div class="col-md-1">
            Select Faclty
        </div>
        <div class="col-md-3">
            <asp:DropDownList ID="ddlFaclty" class="form-control" runat="server"></asp:DropDownList>
        </div>
        <div class="col-md-2">
            <asp:Button ID="btnEnroll" class="btn btn-info" runat="server" Text="Enroll Faculty" OnClick="btnEnroll_Click" />
        </div>
        <div class="col-md-1">
            <asp:Button ID="btnCancel" class="btn btn-warning" runat="server" Text="Cancel" OnClick="btnCancel_Click" />
        </div>
    </div>
    <div class="row">
        <asp:Label ID="lblErrMsg" runat="server" ForeColor="Red"></asp:Label>
    </div>
    <div class="row">
        <asp:GridView ID="gvCourseEnroll" runat="server" class="table" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" HeaderStyle-BackColor="#3AC0F2" HeaderStyle-ForeColor="White" RowStyle-BackColor="#A1DCF2" AlternatingRowStyle-BackColor="White" RowStyle-ForeColor="#3A3A3A" AllowPaging="true" PageSize="10">
            <Columns>
                <asp:TemplateField HeaderText="CFId" Visible="false">
                    <ItemTemplate>
                        <asp:Label ID="lblCrFacId" runat="server" Text='<%#Eval("CF_ID") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="CF_FACULTY_ID" Visible="false">
                    <ItemTemplate>
                        <asp:Label ID="lblFacultyId" runat="server" Text='<%#Eval("CF_FACULTY_ID") %>'></asp:Label>
                        <%--<%#Eval("CF_FACULTY_ID") %>--%>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="CF_COURSE_ID" Visible="false">
                    <ItemTemplate>
                        <asp:Label ID="lblCourseId" runat="server" Text='<%#Eval("CF_COURSE_ID") %>'></asp:Label>
                        <%--<%#Eval("CF_COURSE_ID") %>--%>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Course Name">
                    <ItemTemplate>
                        <%#Eval("CF_COURSE_NAME") %>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Faculty Name">
                    <ItemTemplate>
                        <%#Eval("CF_FACULTY_NAME") %>
                    </ItemTemplate>
                </asp:TemplateField>

            </Columns>
        </asp:GridView>
    </div>
    
</asp:Content>
