<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMaster.Master" AutoEventWireup="true" CodeBehind="FacltyStudentEnroll.aspx.cs" Inherits="OnlineEnrollmentSystem.Admin.FacltyStudentEnroll" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="row">
        <div class="col-md-1">
            Select Faclty
        </div>
        <div class="col-md-3">
            <asp:DropDownList ID="ddlFaclty" class="form-control" runat="server"></asp:DropDownList>
        </div>
        <div class="col-md-1">
            Select Student
        </div>
        <div class="col-md-3">
            <asp:DropDownList ID="ddlStudent" class="form-control" runat="server"></asp:DropDownList>
        </div>
        <div class="col-md-2">
            <asp:Button ID="btnEnroll" runat="server" Text="Enroll Student" class="btn btn-info" OnClick="btnEnroll_Click" />
        </div>
        <div class="col-md-1">
            <asp:Button ID="btnCancel" runat="server" Text="Cancel" class="btn btn-warning" OnClick="btnCancel_Click" />
        </div>
    </div>
    <div class="row">
        <asp:Label ID="lblErrMsg" runat="server" ForeColor="Red"></asp:Label>
    </div>
    <div class="row">
        <asp:GridView ID="gvFacultyStudEnroll" class="table" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" HeaderStyle-BackColor="#3AC0F2" HeaderStyle-ForeColor="White" RowStyle-BackColor="#A1DCF2" AlternatingRowStyle-BackColor="White" RowStyle-ForeColor="#3A3A3A" AllowPaging="true" PageSize="10">
            <Columns>
                <asp:TemplateField HeaderText="CFId" Visible="false">
                    <ItemTemplate>
                        <asp:Label ID="lblCrFacId" runat="server" Text='<%#Eval("FS_ID") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="FS_FACULTY_ID" Visible="false">
                    <ItemTemplate>
                        <asp:Label ID="lblFacultyId" runat="server" Text='<%#Eval("FS_FACULTY_ID") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="FS_STUDENT_ID" Visible="false">
                    <ItemTemplate>
                        <asp:Label ID="lblCourseId" runat="server" Text='<%#Eval("FS_STUDENT_ID") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Faculty Name">
                    <ItemTemplate>
                        <%#Eval("FS_FACULTY_NAME") %>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Student Name">
                    <ItemTemplate>
                        <%#Eval("FS_STUDENT_NAME") %>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
    </div>

    
</asp:Content>
