<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMaster.Master" AutoEventWireup="true" CodeBehind="FacultyList.aspx.cs" Inherits="OnlineEnrollmentSystem.Admin.FacultyList" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
     <table>
        <tr>
            <td>
                <%--<asp:Button ID="btnFaculty" runat="server" Text="Add Faculty" OnClick="btnFaculty_Click" />--%>
            </td>
            <td></td>
        </tr>
        <tr>
            <td>
                <asp:GridView ID="gvFaculty" class="table" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" HeaderStyle-BackColor="#3AC0F2" HeaderStyle-ForeColor="White" RowStyle-BackColor="#A1DCF2" AlternatingRowStyle-BackColor="White" RowStyle-ForeColor="#3A3A3A" AllowPaging="true" PageSize="10">
                    <Columns>
                        <asp:TemplateField HeaderText="FacltyId" Visible="false">
                            <ItemTemplate>
                                <asp:Label ID="lblFacultyId" runat="server" Text='<%#Eval("F_ID") %>' ></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Faclty Name">
                            <ItemTemplate>
                                <%#Eval("F_NAME") %>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="User Name">
                            <ItemTemplate>
                                <%#Eval("F_USERNAME") %>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Email">
                            <ItemTemplate>
                                <%#Eval("F_EMAIL") %>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Phone Number">
                            <ItemTemplate>
                                <%#Eval("F_PHNUM") %>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Address">
                            <ItemTemplate>
                                <%#Eval("F_ADDRESS") %>
                            </ItemTemplate>
                        </asp:TemplateField>                                                
                    </Columns>
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>
