<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMaster.Master" AutoEventWireup="true" CodeBehind="StudentsList.aspx.cs" Inherits="OnlineEnrollmentSystem.Admin.StudentsList" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
     <table>
        <tr>
            <td>
                <%--<asp:Button ID="btnStudent" runat="server" Text="Add Student" OnClick="btnStudent_Click" />--%>
            </td>
            <td></td>
        </tr>
        <tr>
            <td>
                <asp:GridView ID="gvStudent" class="table" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" HeaderStyle-BackColor="#3AC0F2" HeaderStyle-ForeColor="White" RowStyle-BackColor="#A1DCF2" AlternatingRowStyle-BackColor="White" RowStyle-ForeColor="#3A3A3A" AllowPaging="true" PageSize="10">
                    <Columns>
                        <asp:TemplateField HeaderText="StudentId" Visible="false">
                            <ItemTemplate>
                                <asp:Label ID="lblStudentId" runat="server" Text='<%#Eval("S_ID") %>' ></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Student Name">
                            <ItemTemplate>
                                <%#Eval("S_NAME") %>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="User Name">
                            <ItemTemplate>
                                <%#Eval("S_USERNAME") %>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Qualification">
                            <ItemTemplate>
                                <%#Eval("S_QUALIFICATION") %>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Email">
                            <ItemTemplate>
                                <%#Eval("S_EMAIL") %>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Phone Number">
                            <ItemTemplate>
                                <%#Eval("S_PHNUM") %>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Address">
                            <ItemTemplate>
                                <%#Eval("S_ADDRESS") %>
                            </ItemTemplate>
                        </asp:TemplateField>                                                
                    </Columns>
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>
