//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEnrollmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactMaster
    {
        public int CM_ID { get; set; }
        public string CM_FullName { get; set; }
        public string CM_PhoneNumber { get; set; }
        public string CM_Email { get; set; }
        public string CM_Message { get; set; }
        public string CM_Discription { get; set; }
        public string CM_AdminMessage { get; set; }
        public string CM_EmailStatus { get; set; }
        public string CM_IsActive { get; set; }
        public string CUSER { get; set; }
        public string CDATE { get; set; }
        public string MUSER { get; set; }
        public string MDATE { get; set; }
        public byte[] TIMESTAMP { get; set; }
        public System.DateTime PostDate { get; set; }
        public System.DateTime ReplayDate { get; set; }
    }
}
