//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEnrollmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacultyMaster
    {
        public FacultyMaster()
        {
            this.CourseFacultyEnrollTransactions = new HashSet<CourseFacultyEnrollTransaction>();
            this.FacultyStudentEnrollTransactions = new HashSet<FacultyStudentEnrollTransaction>();
        }
    
        public int F_ID { get; set; }
        public string F_NAME { get; set; }
        public string F_USERNAME { get; set; }
        public string F_PWD { get; set; }
        public string F_DESCRIPTION { get; set; }
        public string F_EMAIL { get; set; }
        public string F_PHNUM { get; set; }
        public string F_ADDRESS { get; set; }
        public string F_AYN { get; set; }
        public string CDATE { get; set; }
        public string CUSER { get; set; }
        public string MDATE { get; set; }
        public string MUSER { get; set; }
    
        public virtual ICollection<CourseFacultyEnrollTransaction> CourseFacultyEnrollTransactions { get; set; }
        public virtual ICollection<FacultyStudentEnrollTransaction> FacultyStudentEnrollTransactions { get; set; }
    }
}
