//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEnrollmentSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ONLINEENROLLMENTEntities : DbContext
    {
        public ONLINEENROLLMENTEntities()
            : base("name=ONLINEENROLLMENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourseFacultyEnrollTransaction> CourseFacultyEnrollTransactions { get; set; }
        public virtual DbSet<CourseMaster> CourseMasters { get; set; }
        public virtual DbSet<FacultyMaster> FacultyMasters { get; set; }
        public virtual DbSet<FacultyStudentEnrollTransaction> FacultyStudentEnrollTransactions { get; set; }
        public virtual DbSet<StudentEnrollCourseTran> StudentEnrollCourseTrans { get; set; }
        public virtual DbSet<StudentMaster> StudentMasters { get; set; }
        public virtual DbSet<ContactMaster> ContactMasters { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
