//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEnrollmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentEnrollCourseTran
    {
        public int SEC_ID { get; set; }
        public int SEC_STUDENT_ID { get; set; }
        public string SEC_STUDENT_NAME { get; set; }
        public int SEC_COURSE_ID { get; set; }
        public string SEC_COURSE_NAME { get; set; }
        public Nullable<int> SEC_COURSE_PRICE { get; set; }
        public System.DateTime SEC_ENROLLDATE { get; set; }
        public string SEC_ENROLLBY { get; set; }
        public string SEC_DESCRIPTION { get; set; }
        public string SEC_AYN { get; set; }
        public string CDATE { get; set; }
        public string CUSER { get; set; }
        public string MDATE { get; set; }
        public string MUSER { get; set; }
    
        public virtual CourseMaster CourseMaster { get; set; }
        public virtual StudentMaster StudentMaster { get; set; }
    }
}
