//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEnrollmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMaster
    {
        public StudentMaster()
        {
            this.FacultyStudentEnrollTransactions = new HashSet<FacultyStudentEnrollTransaction>();
            this.StudentEnrollCourseTrans = new HashSet<StudentEnrollCourseTran>();
        }
    
        public int S_ID { get; set; }
        public string S_NAME { get; set; }
        public string S_USERNAME { get; set; }
        public string S_PWD { get; set; }
        public string S_DESCRIPTION { get; set; }
        public string S_EMAIL { get; set; }
        public string S_QUALIFICATION { get; set; }
        public string S_PHNUM { get; set; }
        public string S_ADDRESS { get; set; }
        public string S_AYN { get; set; }
        public string CDATE { get; set; }
        public string CUSER { get; set; }
        public string MDATE { get; set; }
        public string MUSER { get; set; }
    
        public virtual ICollection<FacultyStudentEnrollTransaction> FacultyStudentEnrollTransactions { get; set; }
        public virtual ICollection<StudentEnrollCourseTran> StudentEnrollCourseTrans { get; set; }
    }
}
