//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEnrollmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int U_ID { get; set; }
        public string U_USERNAME { get; set; }
        public string U_PASSWORD { get; set; }
        public string U_FIRSTNAME { get; set; }
        public string U_LASTNAME { get; set; }
        public string U_EMAIL { get; set; }
        public string U_PHNUM { get; set; }
        public string U_ADDRESS { get; set; }
        public int U_ROLE_ID { get; set; }
        public string U_ROLE_NAME { get; set; }
        public string U_ISACTIVE { get; set; }
        public string CUSER { get; set; }
        public string CDATE { get; set; }
        public string MUSER { get; set; }
        public string MDATE { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
